name: Build Packages
on:
  - push
  - pull_request

jobs:
  build:
    name: Build ${{ matrix.pkg }} for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
         # - aarch64
        pkg:
          - static-web-server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0  # fetch all history

      - name: Install Alpine Linux Edge for ${{ matrix.arch }}
        uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.arch }}
          branch: edge
          packages: >
            alpine-sdk
            cargo
            build-base
            gcc
          shell-name: alpine

      - run: adduser runner abuild
        shell: alpine --root {0}

      - run: mkdir -p ~/.abuild && echo -en ${{ secrets.PACKAGER_PRIVKEY }} > ~/.abuild/key.rsa
        shell: alpine {0}


      - name: Build ${{ matrix.pkg }}
        env:
          PACKAGER: ${{ secrets.PACKAGER }}
          PACKAGER_PRIVKEY: ~/.aports/key.rsa
        run: |
          cd pkgs/${{ matrix.pkg }}
          abuild -r
        shell: alpine {0}

      - uses: svenstaro/upload-release-action@v2
        name: Upload Packages for ${{ matrix.pkg }}
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag: edge
          file: '/home/runner/packages/pkgs/${{ matrix.arch }}/*'
          file_glob: true
          overwrite: true