name: Build Packages
on: 
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.pkg }} for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
        pkg:
          #- static-web-server
          - qemu-openrc
          - node-red
          - zigbee2mqtt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0  # fetch all history

      - name: Install Alpine Linux Edge for ${{ matrix.arch }}
        uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.arch }}
          branch: edge
          packages: >
            alpine-sdk
            tree
          shell-name: alpine

      - run: adduser runner abuild
        shell: alpine --root {0}

      - name: Build Key
        run: |
          echo "$PRIVKEY" > "/home/runner/key.rsa"
          mkdir -p repo/pkgs
        env:
          PRIVKEY : ${{ secrets.PACKAGER_PRIVKEY }}
        shell: alpine {0}


      - name: Build ${{ matrix.pkg }}
        env:
          PACKAGER: ${{ secrets.PACKAGER }}
          PACKAGER_PRIVKEY: /home/runner/key.rsa
          REPODEST: "/home/runner/work/apkrepo/apkrepo"
        run: |
          cd pkgs/${{ matrix.pkg }}
          abuild -r
        shell: alpine {0}
        
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.pkg }}-${{ matrix.arch }}
          path: 'pkgs/${{ matrix.arch }}/*.apk'
    
  apkindex:
    name: Generate APKINDEX
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Alpine Linux Edge for ${{ matrix.arch }}
        uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.arch }}
          branch: edge
          packages: >
            alpine-sdk
            tree
          shell-name: alpine
      - uses: actions/download-artifact@v3
      - name: copy apks in repo dir
        run: |
          mkdir -p repo/pkgs/x86_64
          mkdir -p repo/pkgs/aarch64
      - name: APK index
        run: |
          tree
          cd repo/pkgs/x86_64
          apk index
          cd ..
          cd aarch64
          apk index
        env:
          PRIVKEY : ${{ secrets.PACKAGER_PRIVKEY }}
        shell: alpine {0}
