name: Build Packages
on:
  - push
  - pull_request

jobs:
  build:
    name: Build on Alpine ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
          - armv7
        pkg:
          - static-web-server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0  # fetch all history

      - name: Install Alpine Linux Edge for ${{ matrix.arch }}
        uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.arch }}
          branch: edge
          packages: >
            alpine-sdk


      - name: Build ${matrix.pkg}
        run: |
          cd pkgs/${matrix.pkg}
          abuild -r
        shell: alpine.sh {0}
